### ISSUE TITLE
04-Mortgage Calculator

### ISSUE THREAD

**Issue by jeffward01** [OriginCodeAcademy/2015-Fall-Cohort#19]
Where can I find your repository?
https://github.com/jeffward01/04-MortgageCalc 

What new things did you learn from completing this assignment?
I learnt how to convert Doubles to Decimal, and vice versa.  I learnt about manipulating Dates and outputting them.  I also got more practice writing in C# and using functions.  I enjoyed this project.

What did you find difficult about this assignment? 
I found that the formula was initially mildly difficult.  Then after that it was pretty straightforward.  I also encountered an error "TypeInitializationError in mscorlib.dll" had occurred.  I have no idea what that means.  Luckily it occurred just as I completed the first extra of printing out the quote to screen (also added a print X # of months feature).

Did you manage to complete extras? If so - what else would you add to the application?
I completed 1 of the 2 extras.  I could/would of completed the second one, but the error I spoke about earlier was occurring every time I executed the function, preventing it from running.  I would love to fix the error, and then add the 2nd extra.  I will also add a feature to save the quote as a custom user specified nameFile.  Also would like to add an "Email me my quote" feature.

<img width="401" alt="screen shot 2015-09-27 at 9 21 20 pm" src="https://cloud.githubusercontent.com/assets/12589359/10127855/c0588b5c-655d-11e5-8f6c-97734e2f42e8.png">

<img width="1024" alt="screen shot 2015-09-27 at 9 21 28 pm" src="https://cloud.githubusercontent.com/assets/12589359/10127854/c05813b6-655d-11e5-87cf-1442447bc98d.png">

**Comment by cameronoca** [comment]
This was a strange one!

I think we discovered this was due to creating a packaged Console application instead of a simple Console app.
